# Name of your workflow
name: Unit Tests

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    # Job to print something out
    docker-unit-tests:
        runs-on: ubuntu-latest
        name: Build and run unit tests Docker image
        steps:
          - name: 
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t unit-tests-image -f Dockerfile .

          - name: Run image
            run: docker run --rm unit-tests-image